version: '2'
services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    volumes:
      - /opt/rocketchat/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
      - HTTP_PROXY=http://proxy.domain.com
      - HTTPS_PROXY=http://proxy.domain.com
    links:
      - mongo:mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"
  mongo:
    image: mongo:3.2
    volumes:
     - /opt/mongo/data/db:/data/db
  #    - ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ {   _id: 0, host: ''localhost:27017'' } ]})"'
    links:
      - mongo:mongo
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before   starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=general
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
      - RESPOND_TO_DM=true
      - LISTEN_ON_ALL_PUBLIC=true
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot-gitsy
    links:
      - rocketchat:rocketchat
    labels:
      - traefik.backend=hubot
      - traefik.frontend.rule=Host:hubot.bleemeo.work
      - traefik.port=8080
    volumes:
      - /opt/rocketchat/hubot/scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001,   e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080
  gitlab:
    image: 'gitlab/gitlab-ce'
    links:
      - rocketchat:rocketchat
    ports:
      - 443:443
      - 80:80
      - 22:22
    volumes:
      - /opt/gitlab/config:/etc/gitlab \
      - /opt/gitlab/logs:/var/log/gitlab \
      - /opt/gitlab/data:/var/opt/gitlab \
